### ISSUE TITLE
封面图片的加载方式

### ISSUE THREAD

**Issue by montaro2017** [wgh136/pica_configs#4]
目前只发现章节内图片会使用onImageLoad方法，而封面图片则不会
因此导致封面图片无法正常显示，需要为封面图片加载也添加一个方法

**Comment by montaro2017** [comment]
![image](https://github.com/wgh136/pica_configs/assets/35142778/80f3ac5e-9cfc-4d39-8508-782a53afa1dd)

**Comment by wgh136** [comment]
下次app更新时加入此功能

**Comment by montaro2017** [comment]
@wgh136 还有下面图片预览 comic.loadInfo的thumbnails
以及评论的avatar

**Comment by wgh136** [comment]
模板已更新, 增加了`onThumbnailLoad`方法
