### ISSUE TITLE
不分章节EP的漫画源该怎么写chapters

### ISSUE THREAD

**Issue by montaro2017** [wgh136/pica_configs#5]
漫画源不分章节，看到nHentai也是不分章节的，下面不会显示章节
而自定义的漫画源似乎必须要有chapters的值，试过直接用`{}`还是会有一个空白的章节显示在下面

![image](https://github.com/wgh136/pica_configs/assets/35142778/0ce1b5f0-8ccb-4a5f-8b8e-6bcd7d4af416)

**Comment by montaro2017** [comment]
![image](https://github.com/wgh136/pica_configs/assets/35142778/89cf2b18-4230-4998-b7ed-74eae2ef68fc)

**Comment by wgh136** [comment]
删掉chapters字段就可以了

**Comment by montaro2017** [comment]
> 删掉chapters字段就可以了

删除后会报错
![23441507b6b9818efcd728c444cd3ab4](https://github.com/wgh136/pica_configs/assets/35142778/2f95dd40-b426-4db4-b7c4-a424bdc45666)

**Comment by wgh136** [comment]
确实有问题, 下个版本修复, 并且如果提供为空, 也不会显示章节
