### ISSUE TITLE
JS中的中文在APP中变成乱码

### ISSUE THREAD

**Issue by montaro2017** [wgh136/pica_configs#6]
文件编码确定为UTF-8
通过`设置-漫画源-选择文件`方式加载的JS，会把JS中的中文显示为乱码

![image](https://github.com/wgh136/pica_configs/assets/35142778/020fef38-c6a8-47eb-9450-f9dd4267fbb7)

![image](https://github.com/wgh136/pica_configs/assets/35142778/c558e475-cfca-49d3-93f6-02b39fee9898)

**Comment by montaro2017** [comment]
PC端不会乱码

**Comment by wgh136** [comment]
测试了一下, 应该是移动端用于选择文件的`file_selector`库的问题, 下个版本修复
