### ISSUE TITLE
收藏后页面按钮应变为取消收藏

### ISSUE THREAD

**Issue by montaro2017** [wgh136/pica_configs#7]
自定义漫画源，详情页面点击收藏后，页面上变成已收藏，但是再点击`已收藏`的按钮，右侧出现的按钮还是`收藏`

![image](https://github.com/wgh136/pica_configs/assets/35142778/7530fc09-4487-4edf-986c-8c534e90d9c3)

**Comment by wgh136** [comment]
能把你目前的代码发出来吗, 由于我没有单收藏夹的漫画源, 没办法测试此功能

**Comment by montaro2017** [comment]
https://github.com/Montaro2017/pica_configs/blob/master/noyacg.js
需要登陆账号，注册要邀请码，可以用我的邀请码 e4fa7bfa6

**Comment by Montaro2017** [comment]
探索页面的收藏没有问题了，但是收藏页面的还是有问题
