### ISSUE TITLE
自定义漫画源isFavorite无效

### ISSUE THREAD

**Issue by montaro2017** [wgh136/pica_configs#8]
通过comic.loadInfo返回的值，isFavorite为true
详情页面还是显示为`收藏`按钮，应显示为`已收藏`

![image](https://github.com/wgh136/pica_configs/assets/35142778/f996dbda-ef81-4f16-a5b8-ae2d6cddd2ce)

![image](https://github.com/wgh136/pica_configs/assets/35142778/0a3a206a-19c8-4ed6-a6e3-4c9995740b03)

![image](https://github.com/wgh136/pica_configs/assets/35142778/d544df33-cea4-4804-b3ed-daf13f595981)

**Comment by Montaro2017** [comment]
探索页面的收藏没有问题了，但是收藏页面的还是有问题
